spring.application.name=AwsProj01-s3Bucket

cloud.aws.credentials.access-key=AKIA44DBIEJ7CNOVQ7EA
cloud.aws.credentials.secret-key=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
cloud.aws.region.static=ap-southeast-2

aws.bucket.name=sps-s3bucket-proj01