spring.application.name=AwsProj04-rdsMysqlWithEc2

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=rootroot
spring.datasource.url=jdbc:mysql://database-2.czcoomkcw0xn.ap-south-2.rds.amazonaws.com/spsdb
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect